site_name: Auto Translate - 0.1.1
site_url: http://127.0.0.1:8009/fr/
site_description: Project Docs auto generation and translation
site_author: Jason Joy Atsu Winmorre
repo_name: winmorre/generate-and-translate-docs
repo_url: https://github.com/winmorre/generate-and-translate-docs
edit_uri: https://github.com/winmorre/generate-and-translate-docs/blob/main/README.md
nav:
- Maison: index.md
- Languages:
  - en: /
  - fr: /fr/
  - pt: /pt/
theme:
  features:
  - search.suggest
  - search.highlight
  - search.share
  - content.code.annotate
  name: material
  language: fr
  locale: fr
  logo: https://dynaconf.com/img/logo_square_d.svg
  favicon: https://dynaconf.com/img/favicon.ico
  palette:
  - scheme: default
    media: '(prefers-color-scheme: light)'
    primary: white
    accent: teal
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - scheme: slate
    media: '(prefers-color-scheme: dark)'
    primary: black
    accent: teal
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
markdown_extensions:
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tilde
- admonition
- codehilite:
    guess_lang: false
- toc:
    permalink: true
plugins:
- search:
    lang: en
    prebuild_index: true
extra:
  disqus: dynaconf
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/dynaconf/dynaconf
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/rochacbruno
  - icon: fontawesome/brands/linkedin
    link: https://linkedin.com/in/rochacbruno
  - icon: fontawesome/brands/twitch
    link: https://twitch.tv/codeshow
  alternate:
  - link: /
    name: en - English
  - link: /fr/
    name: fr
  - link: /pt/
    name: pt
